import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Main from "../src/components/Main";
import arrow from "../src/images/up-arrow-white.webp";
import { goUp, goDown } from "../src/utils/SlidesUtils";
import Contacts from "../src/components/Contacts";
import Projects from "../src/components/Projects";

export default function Home() {
  const [main, setMain] = useState("active");
  const [projects, setProjects] = useState("up");
  const [contacts, setContacts] = useState("down");
  const [hideTop, setHideTop] = useState(false);
  const [hideBottom, setHideBottom] = useState(false);

  useEffect(() => {
    projects === "active" ? setHideTop(true) : setHideTop(false);
  }, [projects]);

  useEffect(() => {
    contacts === "active" ? setHideBottom(true) : setHideBottom(false);
  }, [contacts]);

  return (
    <div className="index">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
          src={arrow}
          alt="arrow up"
          width={50}
          height={30}
          className={hideTop ? "hide_arrow_up" : "arrow_up"}
          onClick={() => goUp(main, setMain, setProjects, setContacts)}
        />
      <Main
        main={main}
        setMain={setMain}
        setProjects={setProjects}
        setInfo={setContacts}
      />
      <Contacts info={contacts} />
      <Projects projects={projects} />
      <Image
          src={arrow}
          alt="arrow down"
          width={50}
          height={30}
          className={hideBottom ? "hide_arrow_down" : "arrow_down"}
          onClick={() => goDown(main, setMain, setProjects, setContacts)}
        />
    </div>
  );
}
